
name: AmanPandey7647

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "TG_TG_TG_TG_BOT_TOKEN_BF_HER_BF_HER_BF_HER_BF_HER"

          replace: "TG_BOT_TOKEN_BF_HER"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: AmanPandey7647

          commit_user_email: paman7647@gmail.com
